// <auto-generated />
using System;
using Keodou.Notes.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Keodou.Notes.Web.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20230131134525_AddedEntries")]
    partial class AddedEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Keodou.Notes.Web.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("845d105e-1943-40af-b7f1-c76ece311183"),
                            Login = "sa",
                            Password = "sa"
                        },
                        new
                        {
                            Id = new Guid("dcda2ef5-4727-4be4-839f-bbc351a755e0"),
                            Login = "sa2",
                            Password = "sa2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
